build: fix multiple definitions
Fix GCC release 10 being unable to compile iproute-mptcp because of multiple definition of functions.

/usr/bin/ld: ipxfrm.o:(.bss+0x0): multiple definition of `filter'; ipmroute.o:(.bss+0x0): first defined here
/usr/bin/ld: xfrm_monitor.o:(.bss+0x0): multiple definition of `listen_all_nsid'; ipmonitor.o:(.bss+0x0): first defined here
/usr/bin/ld: libutil.a(utils.o):(.bss+0xc): multiple definition of `pretty'; tipc.o:tipc.c:28: first defined here

References: https://bugzilla.opensuse.org/1160244

Signed-off-by: Arınç ÜNAL <arinc.unal@gmail.com>