lnstat: Fix compiler errors of unused return-values
Many errors when compiling with gcc 4.7.3 about unused return-values
upon the calls to fgets:

lnstat_util.c: In function ‘lnstat_scan_fields’:
lnstat_util.c:145:7: error: ignoring return value of ‘fgets’, declared with attribute warn_unused_result [-Werror=unused-result]
lnstat_util.c: In function ‘lnstat_update’:
lnstat_util.c:97:10: error: ignoring return value of ‘fgets’, declared with attribute warn_unused_result [-Werror=unused-result]
lnstat_util.c:111:9: error: ignoring return value of ‘fgets’, declared with attribute warn_unused_result [-Werror=unused-result]
lnstat_util.c: In function ‘scan_lines’:
lnstat_util.c:52:8: error: ignoring return value of ‘fgets’, declared with attribute warn_unused_result [-Werror=unused-result]
cc1: all warnings being treated as errors
make[1]: *** [lnstat_util.o] Error 1
make[1]: Leaving directory `/home/christoph/workspace/linux/iproute2/misc'
make: *** [all] Error 2

Signed-off-by: Christoph Paasch <christoph.paasch@uclouvain.be>